### ISSUE TITLE
Morning Dew Hubs template by JC not loading into Spoke

### ISSUE THREAD

**Issue by jessicasymons** [mozilla/Spoke#1008]
**Description**
Error message comes up when try to remix Morning Dew scene in Spoke

**To Reproduce**
https://hubs.mozilla.com/scenes/PwDk4BG/morning-dew
Remix in Spoke
3. See error

**Expected behavior**
To be able to remix Morning Dew scene

**Screenshots**
![image](https://user-images.githubusercontent.com/54954604/88897505-47f37200-d243-11ea-826e-626f6f0f8a8c.png)

**Hardware** 
 - Device: Desktop
 - OS: Windows 10 Pro
 - Browser: Chrome

**Additional context**

**Comment by j-conrad** [comment]
Looks like the Sketchfab model owner marked the main model as Private so it cannot be downloaded anymore, and therefore, cannot be remixed in Spoke.

I went through the Admin tool and turned OFF remixable, but left the scene as-is since it will currently load in Hubs just fine.
