### ISSUE TITLE
DEMUXER ERROR COULD NOT OPEN: FFmpegDemuxer: open context failed

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/Spoke#1012]
Spokes having video issues - this is  the error message - Spokes wont let me copy the text
![vidoe erro](https://user-images.githubusercontent.com/66266175/89908671-0faa4700-dbe6-11ea-8608-3bfa4f9fd077.jpg)
.

**Comment by InfiniteLee** [comment]
closing, duplicate issue: #964
