### ISSUE TITLE
Lightmaps get ignored on export when using PBR shader

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#1023]
If you have a model using a built-in lightmap (exported from Blender using our hubs-blender-exporter add-on), if you are using a BSDF shader (PBR), it will be ignored by Spoke when publishing to Hubs.
The lightmap will show as expected inside Hubs, so there must be something getting ignored or stripped out at publish time.
(Two .glb objects attached for reference)

The object on the right is using an unlit shader (Background node in Blender), whereas the lefthand object is using the Standard material (BSDF node in Blender):
![image](https://user-images.githubusercontent.com/31968496/92662856-9f5e1680-f2b4-11ea-812a-f36e1069eafa.png)

Note: Hubs will recognize the object's lightmaps correctly if you simply drag/drop them into Hubs:

(Foreground is the dropped-in object):
![image](https://user-images.githubusercontent.com/31968496/92662969-e0eec180-f2b4-11ea-8876-6591412151b2.png)

[Lightmapped_Objects.zip](https://github.com/mozilla/Spoke/files/5198279/Lightmapped_Objects.zip)

**Comment by LAGENCECREE** [comment]
here bug with currents version of HUB/SPOKE :( 
( mesh with two uvs exported from blender 2.90.1 + unlit material via background + MOZ lightmap  + hubs blender exporter 0.0.4 and import/export gltf 2.0 v.1.3.48 ). 
show ok on spoke, not on hub :(

**Comment by keianhzo** [comment]
@LAGENCECREE Can you create an example scene an tag it as remixable so we can take a look?
