### ISSUE TITLE
No Media Frame in Scene Editor

### ISSUE THREAD

**Issue by k888885** [mozilla/Spoke#1035]
I have noticed that Spoke had an update and it added a Media Frame feature, but the same feature is not accessible in Scene editor.

**Comment by netpro2k** [comment]
We deploy changes to hubs cloud about once a month. This feature has not yet rolled out to Hubs Cloud. You can keep an eye on https://github.com/mozilla/hubs-cloud/blob/master/CHANGELOG.md for updates, or join our discord where we also announce upcoming releases.
