### ISSUE TITLE
Youtube Video Links do not work 

### ISSUE THREAD

**Issue by lokesh199414** [mozilla/Spoke#1041]
i am Trying to link a video in my scene with the following youtube URL https://www.youtube.com/watch?v=mIjuMzbhf7A&t
however it shows an error that the quota has been exhausted, please help on the same

**Comment by misslivirose** [comment]
This is a result of YouTube quotas being reached for Hubs. There is more information about this and workarounds here: https://github.com/mozilla/hubs/discussions/2681
