### ISSUE TITLE
Enhancement - Extend Links functionality

### ISSUE THREAD

**Issue by dprado75** [mozilla/Spoke#1049]
Links are a gateway between a Hub's Room and other rooms (or external content). 
I believe these small changes may provide a huge benefit for room customization and functionality:

- optional image to act as a thumbnail instead of capturing a snapshot of the link.
- option to hide the standard "click to open" button, as the image may already include a "call to action" text
- option to hide the "refresh" button.

**Comment by misslivirose** [comment]
Will be implemented with #1101

**Comment by misslivirose** [comment]
The core functionality of adding an href link to an image or video component will be implemented as a V1. We will be revisiting menu options in a future iteration, so for now the buttons will remain the same.
