### ISSUE TITLE
Trigger Volume element is completely missing on some people's Spoke accounts

### ISSUE THREAD

**Issue by mishawagon** [mozilla/Spoke#1051]
Amazing work on Spoke/Hubs y'all! This is an epic platform. 
I see Trigger Volume element and can add it to projects, but at least three of my students do not. We tried in Firefox and Chrome (even compared and found we had consistent versions of Chrome). Our workaround was they give me an export of their project as Spoke legacy .spoke, I import it to my Spoke, I drop in the Trigger Volume, and then export it out as a .spoke and send it to them. 

I tried and can not figure out what our difference is and why they are not seeing trigger volume at all. The only thing I can think of is some kind of opaque slow upgrade rollout from your end enabling/disabling features for some and not others, or perhaps something else.

**Comment by misslivirose** [comment]
The trigger volume is an experimental feature - have you confirmed that the accounts that do not see it have enabled the 'Experimental Features' checkbox under 'Developer > Enable Experimental Features'? That should be the only time that it appears within the editor.

**Comment by mishawagon** [comment]
Ahh that was it! Thank you
