### ISSUE TITLE
How to upload a 3d movel(any format)that I made to Spoke

### ISSUE THREAD

**Issue by kcsgithub** [mozilla/Spoke#1105]
Hello,
I want to make a virtual gallery, but I think it is much easier if I use cinema 4d or sketcup to make my own objects, and then I upload them on Spoke. 
I found that Spoke accept glTF file format, but when I tried to upload the file, I could not select that file at all(grey colored).

Is there any other way that I can use my own created objects in Spoke? I think it's too hard to use the basic building tools and material in Spoke.... :-C 

Thank you for your time!!

**Comment by misslivirose** [comment]
Hey @kcsgithub - Spoke accepts binary glTF models, so it expects the .glb extension. You'll want to export your models in that format, and there are also some tools for converting a .gltf extension to the .glb binary. Hope that helps!

**Comment by kcsgithub** [comment]
> Hey @kcsgithub - Spoke accepts binary glTF models, so it expects the .glb extension. You'll want to export your models in that format, and there are also some tools for converting a .gltf extension to the .glb

**Comment by kcsgithub** [comment]
Thank you!
I don't know the difference between glTF format in Cinema 4d and binary glTF....!
but when I exported a glb format file from Cinema 4d, and then import it on Spoke. It read that file!  I think I can use this now! Is there any limit of file size to upload it on Spoke? I mean the whole file size...?

**Comment by misslivirose** [comment]
The publishing file size limitation for Spoke is 128MB but off the top of my head, I can't recall if that's total or individual file size limits.

**Comment by kcsgithub** [comment]
Hi I solved the problem, I could use GLG format, GLTF didn't work !!
Thank you for all
