### ISSUE TITLE
Why I cannot get up the stairs in Spoke when I made them.

### ISSUE THREAD

**Issue by kcsgithub** [mozilla/Spoke#1109]
Hi all,
I created this scene, https://hubs.mozilla.com/ZUWu2yX/fast-luxurious-cosmos
just for the test, as you can see you cannot get up the stairs, I just pass through them.

When I watched the tutorial about using architectural kit in Spoke https://vimeo.com/371970652 by Hub staff, 
One of the staff said 'I guess we cannot get up the stairs now' when he first created the stairs (at time code 40:36) 
but actually, it worked very well and there's no issue. So I am guessing there's a kind of option that I need to check when I create stairs??? 

Can any one of you let me know what I am missing or what I am doing wrong? :-C 
Thank you for your time in advance!
It's very sad that I even could not manage to create simple stairs...

**Comment by misslivirose** [comment]
You will need to update the floor plan for stairs to work. There is some additional information about that here: https://hubs.mozilla.com/docs/physics-and-navigation.html, but you'll want to play with the step height in the floor plan generator. 

If you have any follow-up questions about using the floor plans or other questions about using Spoke, please create a question in the 'Spoke' discussion board here: https://github.com/mozilla/hubs/discussions/categories/spoke-questions.
