### ISSUE TITLE
If Hubs Cloud is offline, but AWS says it is running, how do i fix

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/Spoke#1126]
So since starting with Hubs Cloud, it seems like it's offline more than it's online. 

If Hubs Cloud is offline, but AWS on the console says it is running, how do I fix it? When I go to the software on Amazon console it times out.

Is this just happening for me or do other users have problems with Hubs Cloud being totally flaky?

**Comment by BonzoMartini** [comment]
it comes on for a few mins then goes offline

**Comment by johnshaughnessy** [comment]
Duplicate of https://github.com/mozilla/hubs/issues/4097
