### ISSUE TITLE
Hubs Cloud is offline

### ISSUE THREAD

**Issue by BonzoMartini** [mozilla/Spoke#1128]
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline
Hubs Cloud is offline

**Comment by johnshaughnessy** [comment]
Duplicate of https://github.com/mozilla/hubs/issues/4097
