### ISSUE TITLE
[Hubs Cloud] Spoke Projects page: Cannot read property 'scene_id' of null

### ISSUE THREAD

**Issue by leonardoazzi** [mozilla/Spoke#1134]
Hi everyone,

After the latest update, when I try to load the Spoke Projects page in my Hubs Cloud I find the following message: "Cannot read property 'scene_id' of null".

![image](https://user-images.githubusercontent.com/13557537/115715231-5132ea80-a34e-11eb-88f1-dce533d4cb8f.png)
![image](https://user-images.githubusercontent.com/13557537/115715280-5c861600-a34e-11eb-987c-b276220e6b9e.png)

My browser is warning that this could be a CSP issue. How can I solve this?

Thank you for your time.

**Comment by netpro2k** [comment]
Can you look in your network tab and see what the response to the "projectless" scenes endpoint looks like? 
![image](https://user-images.githubusercontent.com/130735/115805401-bf50cf00-a399-11eb-905b-2b7cdfcc5c3a.png)

**Comment by leonardoazzi** [comment]
Hi @netpro2k ,

Here it is. 
![image](https://user-images.githubusercontent.com/13557537/116252886-5c1ebe00-a746-11eb-9aad-a31473aa4a58.png)

Thank you for your attention.

> Can you look in your network tab and see what the response to the "projectless" scenes endpoint looks like?
> ![image](https://user-images.githubusercontent.com/130735/115805401-bf50cf00-a399-11eb-905b-2b7cdfcc5c3a.png)
