### ISSUE TITLE
Cannon configure sounds from dynamic videos

### ISSUE THREAD

**Issue by maucascemiro** [mozilla/Spoke#1160]
I've been workin on a virtual exposition for 40 days, and out of the blue i  do not have acces to some features like the AUTO PLAY box when I place a dynamic youtube video. Another problem is the fact that I cant configure my videos in order to only be able to hear it near. Pls help

**Comment by keianhzo** [comment]
This PR https://github.com/mozilla/Spoke/pull/1161 will restore this properties. Make sure the you edit the scene and set those values back to their original state if you published that scene.

**Comment by keianhzo** [comment]
This has been merged so if you open your scene in Spoke now, you should see the auto-play checkbox again and you can check it for the media elements that were unchecked.
