### ISSUE TITLE
Problem with videos

### ISSUE THREAD

**Issue by BtFelipe** [mozilla/Spoke#1162]
Hi

I'm getting an error message that says "e is not iterable" when I click 'publish to hubs'. In my scene project I have about 9 videos running from youtube. I'm not working with code, just adding and changing elements of a pre-made scene, like light values, floor color, etc. Does anyone have any idea what it could be?

**Comment by matthewbcool** [comment]
Hi @BtFelipe, may I ask what your floor plan looks like for that scene?

**Comment by BtFelipe** [comment]
I deleted the floor and added 'ground plane', now everything works fine! thank you :)
