### ISSUE TITLE
CORS Content Security Policy: The page’s settings blocked the loading of a resource at https://hubs.local:9090/assets/js/

### ISSUE THREAD

**Issue by albirrkarim** [mozilla/Spoke#1215]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/29292018/152461770-f255bf1c-4343-48fb-a79c-3031058f3992.png">

From this url 
https://hubs.local:4000/spoke/projects/3yq23c7

Cant loading js resource from hubs.local:9090 which is spoke 
Content Security Policy: The page’s settings blocked the loading of a resource at https://hubs.local:9090/assets/js/vendors~package-kit-page-3d292678844e308c582a.js (“default-src”).

**Comment by jywarren** [comment]
Hi, i'm seeing something similar perhaps - a different result but also a CORS error, for many pages:

![image](https://user-images.githubusercontent.com/24359/152830947-60be074e-16cb-41f2-b8f2-21edde636e39.png)

**Comment by jywarren** [comment]
As well as upon uploading assets, which could be a clue? 
![image](https://user-images.githubusercontent.com/24359/152831906-8f1755d3-23e4-4066-a90c-c40b0142ccf1.png)

**Comment by jywarren** [comment]
This isn't happening anymore -- i logged in again so perhaps something had gone wrong with my session originally?

Matt Cool wrote back on twitter: https://twitter.com/MattBCool/status/1490752945591255043

> Thanks Jeffery! I'm not seeing any errors here, try logging back into your account. 401 is an auth error so you may not be logged in.

I was logged in however, but good to know. My issue resolved but I'll update here again if it happens again and can copy more error logs in.

**Comment by albirrkarim** [comment]
I already fixed this issue

**Comment by albirrkarim** [comment]
1. By using [this](https://hexdocs.pm/phoenix/using_ssl.html#ssl-in-development)  then using that certificate and key for all project.
2. Replacing all `hubs.local` domain with `localhost` 

on every reticulum, hubs, hubs admin, dialog, spoke

**Setting certificate & key path**

For the project that using elixir and phoenix like reticulum setting certificate & key file path on `dev.exs`
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/29292018/152963712-cef5f48d-b160-49f6-be38-dd75aff14150.png">

For the project that using webpack server like ( spoke, hubs, hubs admin, dialog )

add this extra params

`--https --cert certs/cert.pem --key certs/key.pem`

Example for  spoke
We run spoke project with `yarn start` right ? so we add that extra params for `start` command in `package.json`

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/29292018/152964779-a96ade5b-e704-4de5-b64a-a636ccad2ad3.png">
