### ISSUE TITLE
Cannot delete GLB project

### ISSUE THREAD

**Issue by codeanticode** [mozilla/Spoke#1241]
GLB projects uploaded into Hubs directly from Blender scenes cannot be deleted:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/62246/161657777-507d71fa-b042-4597-b91b-69d7222120f4.png">

**Comment by matthewbcool** [comment]
Thanks so much for reporting- also those scenes look really nice. This is a duplicate issue of #1146. Closing as duplicate.
