### ISSUE TITLE
It is blank?

### ISSUE THREAD

**Issue by TheRealDigitalMaster** [mozilla/Spoke#1269]
**I forked the repository because mozilla is blocked for me, but it is blank. Do I launch it from the website? Or is it an app? I don't know.**

**3d VR editor**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Chrome
 - Browser chrome
 - Version idk

**Additional context**

**Comment by matthewbcool** [comment]
Hi there! instructions for running Spoke locally are available here: https://github.com/mozilla/Spoke/blob/master/docs/README.md#getting-started

Spoke use docs are here: https://hubs.mozilla.com/docs/spoke-creating-projects.html
The live site is here: https://hubs.mozilla.com/spoke

Hope that helps you do whatever it is you were trying to do!

**Comment by TheRealDigitalMaster** [comment]
Ok Thanks :)
