### ISSUE TITLE
Clear up vertical real estate in viewport

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#281]
We should remove the title bar above "viewport" and just put a floating label in the top left corner. (Minor UI improvement)

**Comment by robertlong** [comment]
Hmm. This should probably be temporary. Once you have multiple viewports you will likely want to know which is which. Also if you want to view wireframe/unlit rendering, you'll need a place to stick that menu.

**Comment by gfodor** [comment]
Yeah the idea here isn't to remove the label, but to just draw it as a floating label over the scene (so the actual viewport can have some more vertical space to draw graphics.) so should have minimal downside other than perhaps slightly less readability

**Comment by robertlong** [comment]
I think I'd like to use the toolbar to display additional perspectives (top, bottom, right) and rendering modes (wireframe, shadow map, overdraw, etc.)
