### ISSUE TITLE
Hierarchy auto-collapses in certain circumstances

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#296]
Haven't completely figured out how to reproduce consistently, but sometimes the scene hierarchy collapses when I'm trying to click on items inside it. It seems to happen more when I attempt to move something out of a group.

**Comment by j-conrad** [comment]
Also, when I re-expand the top-level scene item, all groups underneath it auto-expand whereas I believe they should remember their open/closed state.

**Comment by gfodor** [comment]
tried messing around and couldn't repro the first one. going to break your second one out into a new issue

**Comment by gfodor** [comment]
https://github.com/MozillaReality/Spoke/issues/310
