### ISSUE TITLE
Custom pivot point for models

### ISSUE THREAD

**Issue by joshmarinacci** [mozilla/Spoke#382]
depending on how a GLTF model was generated sometimes the center of the model (the origin of the coordinates system) will be far away from the visual center of the model. See the attached screenshot of a common example when using Kenney.nl assets.   There should be some way to recenter a model. This would set the center of the object for both translation, scale, and rotation options.  It should be able to manually set center and also calculate a logical center based on the extents of the model (ThreeJS provides such a function already).

In the attached screenshot you can see that the translation controls are at the origin, but the visual center of the model is five meters to the left.

<img width="1150" alt="firefox nightlyscreensnapz098" src="https://user-images.githubusercontent.com/276938/48532293-a0f35a80-e854-11e8-9aae-4ebc5534bb95.png">

**Comment by brianpeiris** [comment]
See also #212

**Comment by joshmarinacci** [comment]
I really need this. I'm doing a video and almost every model comes in at some weird translation. It makes rotation *super* hard.  Just a button that calls geometry.center() would be awesome.
