### ISSUE TITLE
Avatar spawnpoint orientation does not match actual spawn orientation in Hubs

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#412]
**The key to reproducing this bug has to do with the orientation of your viewport camera at the time of 'Publishing To Hubs'.**
If your viewport camera roughly matches the orientation of your Spawn Point, you will likely not see this bug occur. 
If, instead, you rotate your viewport camera, say 180 from the orientation of your Spawn Point, when you enter your scene, you will be facing the direction of that viewport camera.
The viewport camera should not having any correlation with your avatar orientation.
NOTE: This was occurring in 2d mode with no HMD plugged in.

**Comment by gfodor** [comment]
nice sleuthing!

**Comment by johnshaughnessy** [comment]
bump

**Comment by robertlong** [comment]
The Spoke side of this is already correct, we just need to merge this PR in Hubs as soon as the legacy environments are deprecated or ported over: https://github.com/mozilla/hubs/pull/839
