### ISSUE TITLE
Consider adding a warning or auto-rename for non-Unicode items

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#426]
Dropped [this model](https://sketchfab.com/models/8ed0cbfccfa1449996ff0b06875b1863) into Spoke without looking at its name. I was able to Publish to Hubs with no warnings or errors. It wasn't until I chose 'Create a Room with this Scene' that the scene wouldn't ever load.
Renaming the item in Spoke fixed it.

Perhaps we should auto-rename items like this, or at the very least, spit out a warning or error when attempting to publish the scene.

**Comment by robertlong** [comment]
Looks like this works now 👍
