### ISSUE TITLE
Light falloff requires extreme values to work as expected

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#437]
Using any value other than 0 (infinite) for a light's `Distance` parameter makes the light's effect on surfaces drop off much more quickly than one might intuit from the gizmo itself.
For example, setting a point light's `Distance` value to 2 meters with a light `Intensity` of 1 makes is so that an object hit by that light must be within a few centimeters in order to see any light on the object at all.

This leads to either cranking the `Distance` value much much higher than one might expect they have to, or increasing the `Intensity` value to an unreasonably high value, blowing out the lighting on anything that's right near the light.

It very well may be that we're using the scientific approach to light calculation (perhaps inverse square falloff), but it may be a matter of needing a better way for creators to understand the ramifications of using these values. That, or perhaps take the approach of software like Maya where the user may choose what type of falloff they prefer (Linear, Inverse Square, etc.)

**Comment by robertlong** [comment]
I'm not sure this is a bug. The editor should probably be 1 to 1 with ThreeJS's lighting model. It can be a bit challenging to get the lighting how you want it. Maybe this is more of an issue with the sensitivity of the intensity/distance numeric inputs?

**Comment by robertlong** [comment]
I'm going to close this. I know it's a little different to use physical units, but we want to stay true to what ThreeJS is using.
