### ISSUE TITLE
Animations not working in scene (regression)

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#446]
Adding this scene to Spoke drops the animations: https://sketchfab.com/3d-models/christmas-low-poly-scene-7984bd6024db4b89928ddeb625eebac0

**Comment by robertlong** [comment]
This fix is blocked on this PR, we can either pull it into our fork of Three if we think it's good enough or wait for another solution.
https://github.com/mrdoob/three.js/pull/16639
