### ISSUE TITLE
Tutorial image is blue

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/Spoke#503]
![image](https://user-images.githubusercontent.com/4072106/56765270-85717180-675b-11e9-97e5-050cfa0858fa.png)

Is this an accident or a Gmail Blue™?

**Comment by robertlong** [comment]
It's in the original design from Rian. I think it's pretty cool 🙂

**Comment by robertlong** [comment]
Should we actually change this though? @misslivirose what are your thoughts?

**Comment by misslivirose** [comment]
I don't feel too strongly either way. It might not be immediately obvious to someone that it's a scene that they could build, but it does unify the design. For contrast, here it is in context, with a full color image: 
![image](https://user-images.githubusercontent.com/4313320/56827092-b06acc80-6812-11e9-9cdd-b127621765bb.png)

**Comment by johnshaughnessy** [comment]
The low-contrast blue image made it difficult for me to tell what I was looking at, so I like the full color screenshot misslivirose linked above. But I also don't feel strongly.

**Comment by robertlong** [comment]
I'm going to close this, but I'll make sure we keep it in mind for the next onboarding redesign. Low contrast background images probably aren't a great idea when they don't add much to the visual design.
