### ISSUE TITLE
Surprising auto-generated floor plan

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/Spoke#520]
![image](https://user-images.githubusercontent.com/4072106/56767002-96bc7d00-675f-11e9-9174-a2097c8a09a1.png)

**Comment by robertlong** [comment]
@johnshaughnessy Could you explain what's surprising about the floor plan? The borders around the objects are what I'd expect with the default settings.

**Comment by robertlong** [comment]
I'm going to close this, I think this floorplan was correct for the default settings
