### ISSUE TITLE
Adding and removing a skybox made everything in my scene dark

### ISSUE THREAD

**Issue by johnshaughnessy** [mozilla/Spoke#530]

**Comment by johnshaughnessy** [comment]
Refreshing the page fixed the issue

**Comment by robertlong** [comment]
@johnshaughnessy could you check to see if this is still happening? I think everything is acting as it should. Maybe you had two skyboxes in the scene? That shouldn't be possible after https://github.com/MozillaReality/Spoke/pull/589

**Comment by robertlong** [comment]
I haven't seen this in a while so I'm going to close this.
