### ISSUE TITLE
Show current scene complexity

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#549]
It is very sad to have a scene that you don't realize is too big, and then end up having to delete objects and work backwards. If we could recognize a few warning signs, it could make the experience a little more smooth for users who aren't familiar with some of the things they should do to optimize their scenes.

**Comment by HeadClot** [comment]
So just an idea but why not a view similar to UE4 Scene complexity view? [You can read more about it here](https://docs.unrealengine.com/en-US/Engine/UI/LevelEditor/Viewports/ViewModes/index.html)

Just an idea :)
