### ISSUE TITLE
Snapping can become inverted

### ISSUE THREAD

**Issue by netpro2k** [mozilla/Spoke#559]
Not 100% sure how I did it but managed to get snapping to become inverted. It was resolved after tapping the ctrl key so I assume whatever internal state tracks the ctrl key was stuck on.

**Comment by robertlong** [comment]
I haven't been able to reproduce this. I'm going to move this out of priority for now.

**Comment by robertlong** [comment]
I haven't seen this in a while so I'm going to close this, the Spoke controls were cleaned up since this issue was reported, perhaps we fixed the issue.
