### ISSUE TITLE
"Elements" is different from Videos/Images/Models but presented at the same level

### ISSUE THREAD

**Issue by netpro2k** [mozilla/Spoke#569]
Bit confusing that these are given the same UI treatment and presented as sibling options though they are sort of different concepts. Might just be a matter of sort of visually separating them.

**Comment by robertlong** [comment]
I'm not sure they really are, but I get where you are coming from. All of these tabs spawn objects into the world when you click them, in that regard they are the same. However elements can be an empty model, video, or image as well as lights etc.

What would you like to see here instead?
