### ISSUE TITLE
Tranform fields should not show full floating point value

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/Spoke#619]
Not a big deal, I suppose, but it does look a bit odd to see the full float value in the transform fields. They should be rounded to three decimal places.

**Comment by robertlong** [comment]
Maybe only when you don't have it focused? You probably don't want to lose accuracy there but it does make it cluttered when you are dragging objects around in the editor. I'm still not sure how I feel about this or the correct solution.

**Comment by brianpeiris** [comment]
One reason you might want show more digits is if the number is very small, but does actually have significant figures that you care about. For example, if the default was to round at three decimal places, it should still show 5 decimal places for numbers like 0.00001, since the zeros are insignificant.
Showing the full number on focus also sounds good.
