### ISSUE TITLE
Spoke launches SteamVR

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#665]
I was seeing this on my desktop PC, which has SteamVR installed and my Oculus Rift plugged in. When I go to hubs.mozilla.com/spoke, the website starts SteamVR even though there isn't currently a VR component to Spoke. It's not a huge blocker, but it is kind of annoying because the SteamVR window pops up in front of what I'm trying to do in Spoke and takes a bit to shut down. 

Firefox stable (66.04, I believe - can confirm when I'm back at my desktop there if it's not reproing elsewhere)

**Comment by robertlong** [comment]
I don't think this is still happening. I think more recent versions of FF have fixed this.
