### ISSUE TITLE
'N is undefined' error when exporting object with hierarchy

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#672]
![image](https://user-images.githubusercontent.com/4313320/58510986-bffd6e00-814e-11e9-8caf-125ed7c7ffbd.png)

Repro 100% (Win 10 FF Nightly)
1. Create two 3D models (I used the dresser and lamp)
2. Drag the lamp onto the dresser to create a nested object
3. Attempt to export

I get 'N is undefined'. Another user (who attempted to nest images, rather than 3D models) reported getting the error 'Cannot read property children of undefined'

**Comment by robertlong** [comment]
It looks like this has to do with cloning objects before export. In the `clone()` and `copy()` methods we sometimes exclude editor only objects such as the Loading Cube from being cloned. This is a problem when we want to remap some data (uuid or skeleton data) from the original node to the cloned node.

For example if I have a node with 3 children:

```
Dresser
 .children
  [0] Loading Cube
  [1] Dresser Mesh
  [2] Lamp
```

If I clone the dresser I actually want to remove the Loading Cube.

```
Dresser
 .children
  [0] Dresser Mesh
  [1] Lamp
```

So now when I want to copy data about the Lamp from the original node to the cloned node. It is undefined.

I think we have two options:
1. Never allow removing objects in the `copy()` method, always preserve the scene heirarchy. This could prove to be complex when dealing with objects that are added in the constructor.

For example:
```
export default class PointLightNode extends EditorNodeMixin(PhysicalPointLight) {

  constructor(editor) {
    super(editor);

    this.helper = new SpokePointLightHelper(this);
    this.helper.visible = false;
    this.add(this.helper);
  }

  ...

  copy(source, recursive) {
    super.copy(source, false);

    if (recursive) {
      for (const child of source.children) {
        if (child !== this.helper) {
          const clonedChild = child.clone();
          this.add(clonedChild);
        }
      }
    }

    return this;
  }
}
```

2. Make a more intelligent cloneObject3D. Maybe we can avoid errors by being smart about children that are removed.

3. Make Spoke's scene hierarchy flat. This would avoid some of the complex situations, but I don't know if it will avoid all cloning issues.
