### ISSUE TITLE
[Suggestion] Add 'Fog' component as a scene option

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#686]
The ability to add a distance "fog" element to blend out the horizon feels like it would improve the polish of scenes by giving creators the ability to more easily hide the edges of meshes in their scenes. 

![image](https://user-images.githubusercontent.com/4313320/60037965-e0461d00-9667-11e9-8bff-90714b4a7197.png)

A-Frame Fog Element documentation: https://aframe.io/docs/0.9.0/components/fog.html

**Comment by Shivansh2407** [comment]
Can I work on this issue?

**Comment by j-conrad** [comment]
This was done yesterday.  🎉
