### ISSUE TITLE
360 photo spheres appear upside-down in Hubs

### ISSUE THREAD

**Issue by brianpeiris** [mozilla/Spoke#693]
The photo sphere looks correct in Spoke by default, but it appears flipped upside down when published and viewed in hubs

**Comment by brianbatista** [comment]
I'm also experiencing the same thing, tried with multiple 360 photos.
The only solution I've had so far is to flip the 360 photo in an editing software upsidedown, so that Spoke will "unflip" it.

**Comment by brianpeiris** [comment]
Another workaround is to set the X rotation on the sphere to 180 and also flip the X scale to negative:
![image](https://user-images.githubusercontent.com/79419/61654121-93f2fa80-ac70-11e9-81ad-006db4092e26.png)

**Comment by brianbatista** [comment]
@brianpeiris that worked perfectly. Nice solution :)
