### ISSUE TITLE
integrate spoke into blender 2.8 similar to BGE in pre-2.8?

### ISSUE THREAD

**Issue by BluePrintRandom** [mozilla/Spoke#695]
could you integrate spoke into blender 2.8 similar to BGE in pre-2.8?

Node logic ?

the whole shebang?

**Comment by robertlong** [comment]
Hey @BluePrintRandom we don't have any plans at this time to integrate Spoke into Blender. However, we use Blender 2.8's glTF exporter/importer to get assets into and out of Spoke. https://docs.blender.org/manual/en/dev/addons/io_gltf2.html

We also don't have a timeline for scripting in Spoke/Hubs but it is something we'd like to do. If you are interested in building apps / games around Spoke or Hubs you should join the #scripting channel in our discord: https://discord.gg/vgxfMpr

We'd appreciate any feedback you have!
