### ISSUE TITLE
Error Publishing Project: e is Undefined when setting video audio mode to 'stereo'

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#729]
Repro Steps:

1. Create a new scene in Spoke
2. Add a video
3. Change the audio property from pannernode to stereo
4. Attempt to publish the scene to Hubs

Expected: it publishes with the audio set to stereo
Actual: Error publishing

This repros 100% of the time for me on Firefox Nightly, Windows

![image](https://user-images.githubusercontent.com/4313320/63132791-3738e600-bf77-11e9-8f53-9d5264de166f.png)

**Comment by robertlong** [comment]
Thanks for filing this. I think I've seen this show up in Sentry, I'll fix this one ASAP.
