### ISSUE TITLE
Consider swapping default search from Sketchfab to Google Poly or point to specific Mozilla curated collection

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#732]
When I go to add a model in Spoke, the current search defaults to Sketchfab's 'Featured' API, which contains models that may make people feel uncomfortable using Spoke in a professional environment. 

I would suggest that we point to a specific curated collection that we make on Sketchfab in the default search, or swap the default provider to Google Poly in order to reduce the likelihood that users could be exposed to that content on their first time in Spoke while going through the tutorial. I am happy to help curate and maintain a collection on Sketchfab if we can go that route.

**Comment by emclaren** [comment]
+1

**Comment by robertlong** [comment]
I agree! We originally had it set to our Mozilla Reality curated collection. @gfodor what do you think about changing it back?

**Comment by robertlong** [comment]
We've fixed the default Sketchfab content. I'm going to close this now.
