### ISSUE TITLE
Add a clock entity to Spoke

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/Spoke#733]
**Is your feature request related to a problem? Please describe.**
We would like to have clocks in rooms with schedules, so people know what time it is, especially when in VR where they are cut off from the world.  

Also, in rooms that hold scheduled meetings, it is useful to see a clock in both your current timezone AND the timezone the schedule is being show at, so you know  at a glance when meetings are in your time zone.

**Describe the solution you'd like**
I would like to see a clock object.  It could be digital or analog, with whatever appearance is easiest.  This should be a component that renders the clock in a position defined in Spoke,  in the room, perhaps into a texture, or using whatever method is most appropriate.  The key is that it's running in the hub in all clients, rendering locally (which should be fast and efficient).

The clock should have a predefined timezone, or "local time", as a property in Spoke

**Describe alternatives you've considered**
We've considered streaming a clock app window into a hubs room.  This is a terrible, inefficient solution.

**Additional context**

**Comment by kwadroke** [comment]
Related to Hubs issue #644

**Comment by gfodor** [comment]
A simple clock based upon the user's local clock seems like a sane platform feature in some form (though it's hard to come up with a good place for it that doesn't cause other design tradeoffs.) For more sophisticated features, or in-world clocks, this really lines up with the development track of "creating custom dynamic objects in Hubs + Spoke."

Today the story is pretty weak there: you can fork. We're planning on working more on this, and some initial concepts are materializing -- if we had that this would certainly be a solid use of it.

**Comment by blairmacintyre** [comment]
@gfodor I generally agree with your sentiments.  If we had custom dynamic objects, this would be an easy use case.  I submitted this because the clock struck me as something "unique" and easy to build (and requires zero network communication, and little local processing).  I was imaging two little objects in Spoke (a digital and an analog), that could be placed where the scene creator wants, and the only real options on it is the timezone.

**Comment by robertlong** [comment]
I think we can roll this into https://github.com/mozilla/Spoke/issues/857
