### ISSUE TITLE
Color picker has a delay before opening

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#761]
The color picker for lights has a several second delay before opening.

In Firefox:

1. Create a light (any type)
2. Go to the properties panel
3. Click on the color picker for the light
4. Result:  It can take up to 4-5 seconds before it opens.

Note:  This was fixed but has since regressed.

**Comment by misslivirose** [comment]
@j-conrad still seeing this? I haven't seen it in Nightly

**Comment by robertlong** [comment]
This looks like it is working again. I think I remember there was a specific way to make this happen though. Feel free to reopen if you find out how to reproduce it.
