### ISSUE TITLE
Should not show browser context menu when right-clicking or Shift + right-clicking

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#763]
There are places in the editor where you can use right-click or Shift + right-click, opening the browser context menu and causing all sorts of issues. 
For example, in the 3d view, Shift + right-click will sometimes cause the app to think you still have Shift held down, even after releasing all keys/buttons.
Also, in the Properties or Hierarchy panel (in a non-field area), right-click will open the browser context menu.

**Comment by robertlong** [comment]
Unfortunately we can't fix this. Firefox doesn't allow us to prevent this behavior.
