### ISSUE TITLE
Hard to click and move the change-position arrows on an object

### ISSUE THREAD

**Issue by ducile** [mozilla/Spoke#782]
Since the last update to the new type of arrows it is very hard to click these in order to move the position of an object on a certain axis. I would need to move the camera around many times until it reaches a certain angle where it is possible to click the arrows with the mouse and then move it. I also noticed that the movement is not smooth as well and can be very "jumpy" at certain angles as well, meaning a slight mouse movement would make x=5 jump to x=200.

Attaching a file of the arrows that I'm talking about.
![click](https://user-images.githubusercontent.com/16058129/66585440-d122a680-eb54-11e9-97c1-c2eacf3603f8.png)

**Comment by misslivirose** [comment]
Robert has recently made some improvements to the placement mechanics (#781) but we should keep this open for further iteration and polish. I've seen some big jumps with the arrow dragging too, but with the new placement, it's less frequent.

**Comment by robertlong** [comment]
Highlighting the arrows when you hover over them would also be a big improvement. The old transform gizmo used to to do that and I need to add that back in.
