### ISSUE TITLE
Project name reverts to original when publishing to Hubs

### ISSUE THREAD

**Issue by emclaren** [mozilla/Spoke#795]
Spoke projects default to their original name before being uploaded to Hubs.

I gave this project a unique name
<img width="607" alt="Screen Shot 2019-10-17 at 3 29 58 PM" src="https://user-images.githubusercontent.com/6835324/67053674-ecfaef00-f0f6-11e9-9c4a-261430f719be.png">

In "Publish to Hubs" dialog box, it reverts to WideOpenSpace1
<img width="678" alt="Screen Shot 2019-10-17 at 3 30 07 PM" src="https://user-images.githubusercontent.com/6835324/67053678-ee2c1c00-f0f6-11e9-8922-adb1e87f5f1f.png">

It would be helpful if the project name was carried over when publishing to Spoke. There are currently lots of scenes that share the default template names in Hubs' back end, making it hard to find specific scenes.

**Comment by gfodor** [comment]
this seems like a P1 to
