### ISSUE TITLE
Collision (?) Wireframe showed up in project preview

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#800]
![image](https://user-images.githubusercontent.com/4313320/67115496-3731ae00-f193-11e9-876e-7d5c04675dcf.png)

When I saved a project, this was saved as part of the snapshot. It shows up when I publish the scene to Hubs in the Spoke Viewport too - I'm unsure what I'm doing specifically to cause it in this instance.

**Comment by robertlong** [comment]
@misslivirose I believe this should be fixed now. It was fixed last week but I accidentally didn't push until this morning. Let me know if this occurs again.
