### ISSUE TITLE
GIF Search audio should be off

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#814]
It's quite surprising and loud when the gif search media returns gifs with audio while working in Spoke. We should not play audio through the search results. I think we had this in Hubs too (it may still be active)

**Comment by gfodor** [comment]
this was already fixed in hubs https://github.com/mozilla/hubs/commit/c8e54e62d84bdb07ac78d65ea5cce3d70540acd8#diff-07840b7b51b87691c93935dcaace48e7
