### ISSUE TITLE
Hovering over a thumbnail in asset picker should zoom

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#828]
With the new kit, it's fairly hard to get a good look at some of the thinner/smaller pieces without adding them to the scene. I think we should set things up so that if you hover over a piece, after 1s or so it flips into a mode where mouseover's will pop a bigger thumbnail as you move your mouse over the thumbnails. When your mouse leaves the thumbnail grid, it flips back.

**Comment by robertlong** [comment]
@gfodor this sounds like a good idea. So this would replace the tooltip or would the larger preview just be in the tooltip? You'd probably expect the same view for all asset sources and it'd be easiest if I could implement one component that handled all asset types, what about for elements? They only have a description. Also 1s seems like a while to wait when you are scanning a lot of pieces, but for drag and drop anything shorter might get in the way.

Maybe we could show the tooltip after a very short duration above the assets panel? It would include text content (title, description, author, etc.) as well as a larger thumbnail. Also, I think we can continue to do better on the thumbnails themselves. I think a plain black background in the 3D thumbnails doesn't really work. Perhaps we should use something a little lighter? Maybe I can render with shadows in a studio like environment?

**Comment by gfodor** [comment]
actually maybe we just need to add the thumbnail to the tooltip as a start, that might be just fine. i agree having a nicer background would work. i think a studio rendering would be ideal for sure, not sure how hard that would be.

**Comment by robertlong** [comment]
I split out the improved background into another issue https://github.com/mozilla/Spoke/issues/836 The thumbnail size is addressed in https://github.com/mozilla/Spoke/pull/835
