### ISSUE TITLE
Mouse scrolling in the viewport is too extreme

### ISSUE THREAD

**Issue by misslivirose** [mozilla/Spoke#839]
I haven't done anything specific to my mouse settings (and the scrolling is fine / normal in other applications) but now when I use the mouse wheel in Spoke, the view port scrolling is too extreme. 

Video shows what two scroll 'notches' results in when the ground mesh is selected from the 'Wide Open Space' template, but this also happens when selecting spawn points. 

https://vimeo.com/371921522

Firefox Stable 70.0.1, Windows

**Comment by robertlong** [comment]
@misslivirose could you test this branch on your system and see if it's fixed?
https://github.com/mozilla/Spoke/pull/840

**Comment by misslivirose** [comment]
I had to download and turn off smooth scrolling directly through the mouse software (changing the Windows settings and Firefox settings didn't work, but turning it off through the mouse customization app did)
