### ISSUE TITLE
Fog does not affect particles

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#876]
Adding fog to a scene does not affect the visibility of particle systems, no matter the type or density.

For reference, in the following scene, the fog is set to almost black (very dark red), exponential, and with a density of 0.23. In the up close shot, note the particles and 3d objects are visible. In the farther shot, the 3d objects become obscured by the fog, but not the particles.

![image](https://user-images.githubusercontent.com/31968496/72927903-e7233400-3d0b-11ea-8245-74f53130f918.png)

Up close:
![image](https://user-images.githubusercontent.com/31968496/72927803-b80cc280-3d0b-11ea-96a5-862bbb6efddd.png)

Farther away:
![image](https://user-images.githubusercontent.com/31968496/72927828-c65ade80-3d0b-11ea-912b-6e59e1c2ebf5.png)

**Comment by robertlong** [comment]
This is fixed as of https://github.com/mozilla/Spoke/pull/879
