### ISSUE TITLE
Spoke produces a GLB with invalid KHR lights

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#878]
This scene fails to load: https://hubs.mozilla.com/scenes/fjDs8n3

(May be fixed via workaround at time you click this)

This is the error:

![image](https://user-images.githubusercontent.com/220020/73095421-62fdb780-3e97-11ea-8b55-103d98023593.png)

.spoke file is attached.
[conference-hall-.zip](https://github.com/mozilla/hubs/files/4110173/conference-hall-.zip)

**Comment by brianpeiris** [comment]
Spoke takes this GLB, which contains a KHR_lights_punctual node https://uploads-prod.reticulum.io/files/e35c7b4e-ef75-4b5f-a3a3-ecf361bfcc87.glb and produces this GLB, which references a light that does not exist https://uploads-prod.reticulum.io/files/29f5175f-809a-4d86-96f4-029ba5411dd9.bin
