### ISSUE TITLE
visual feedback for audio settings on video elements

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/Spoke#888]
If I adjust the audio distance and code of effect, it would be great to see what this is in-world in the editor.

**Comment by robertlong** [comment]
@blairmacintyre this is now possible through the experimental preview mode.

https://github.com/mozilla/Spoke/pull/887

**Comment by blairmacintyre** [comment]
I tried it;  I'll file a bug there, since the streaming video doesn't appear to work properly.

But, being able to preview the scene is separate from seeing a visual previous inside of the spoke editor.  I'd like to actually SEE the extent of the audio, for example.
