### ISSUE TITLE
Android scene lighting does not match PC Spoke lighting

### ISSUE THREAD

**Issue by christianv78** [mozilla/Spoke#923]
I'm new to Spoke/Hub. Making my first scene. I have set up the environment lighting in my scene on Spoke and added a spot light, but when I publish and enter the scene on my Android phone, the scene appears to be unlit - everything is bright white. Am I doing something wrong?

**Comment by robertlong** [comment]
This is intended. Hubs is lit on desktop and unlit on mobile for performance reasons. You can force lighting on in the preferences by turning on high quality rendering.
