### ISSUE TITLE
Spoke won't upload my gtLF files or see them in their source folder        

### ISSUE THREAD

**Issue by TruElmore** [mozilla/Spoke#976]
I am trying to build an Spoke environment using my assets. 
However, Spoke won't upload gtLF files and can't see them in their source folder. 

When I try to drag and drop I get this message:

**Error uploading file:  'VRHOUSE.gltf' does not match the following mime types or extensions: .mp3, audio/MPEG, .mp4, .png, .jpg. .gif, image/png, .glb, model/gltf-binary**

what is happening?

**Comment by misslivirose** [comment]
You will need to upload the gltf in a binary format (.glb extension)

**Comment by TruElmore** [comment]
Hi Liv,

But when I convert the files to glb, they import but wont show up in the
scene

T

**Comment by misslivirose** [comment]
Can you validate your models in another 3D viewer? Or share an example of one of the models that you've tried to upload?

**Comment by TruElmore** [comment]
Here is the SketchFab link 

https://sketchfab.com/3d-models/whitehouse-28d4900c7f4d4b3cb3514bcda92577d7

**Comment by misslivirose** [comment]
That link works for me - when I paste the URL into Spoke, it uploads the model. The model has a different offset and is small, but it does show up in the scene. Can you go into more detail about the steps you're following?

**Comment by misslivirose** [comment]
And, are you using hubs.mozilla.com/spoke, or a scene editor on a Hubs Cloud instance?

**Comment by misslivirose** [comment]
This shows up when I import it, but when I try to scale it, it is out of bounds. When I open it in a the Microsoft 3D viewer, it says that it's invalidly defined. This seems like an issue with the model itself - when I open the glTF downloaded from Sketchfab in blender, it doesn't show up there either. When I used the 3D viewer to automatically fix the invalid model, I was able to import it into blender but it was very large. I would recommend dropping into the #art channel in the Hubs Discord: https://discord.gg/wHmY4nd so folks with more experience in exporting models for Spoke can recommend a fix!

**Comment by TruElmore** [comment]
I just spent 300 dollars on a year membership to Sketfab so I could
seamlessly import models, and after troubleshooting for hours I still can
reliably import a single piece.
Do you have a tutorial on this that's up to date and accurate?

**Comment by misslivirose** [comment]
You have two options with models on Sketchfab: 

- If the model is downloadable, you can try to copy and paste the Sketchfab URL directly into Hubs or Spoke. If the file is a valid .glTF, this will work. As I mentioned, the importing of the model you linked above does work in Spoke, but the glTF itself is not a valid glTF model and is scaled out of bounds in Spoke when you try to change the size. This is often the case with an auto-converted or older version of the glTF standard.

- If you are able to modify the model on your computer directly, we have documentation for making models export properly with our Blender add-on: https://hubs.mozilla.com/docs/creators-using-the-blender-gltf-exporter.html and you can find additional information about optimizing scenes here: https://hubs.mozilla.com/docs/spoke-optimization.html 

As much as we try to handle things in Spoke properly, if the model itself is not a valid glb, we won't be able to render them in Spoke/Hubs. 

I would definitely recommend checking out the Discord server linked above to get recommendations on the specific models you're trying to use! That channel is monitored by more folks on the team who have more experience working with 3D assets who can provide more tailored assistance.

**Comment by TruElmore** [comment]
Thanks, Liv.

I appreciate your help, I do.
Yesterday I paid for Sketchfab Plus, then had to upgrade to Pro, in order
to establish the link paste pipeline for models into Spoke.
Even then, it won't work reliably.
That is to say, it hasn't worked once.

Now it's looking like I'll have to download and learn Blender in order to
get a working model up.
Your customer service is excellent, but the platform is severely lacking
and quite frustrating.

I won't be recommending it.






<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
