### ISSUE TITLE
Spot Light intensity uses degrees rather than candela

### ISSUE THREAD

**Issue by robertlong** [mozilla/Spoke#986]
We need to change the unit of the input.

**Comment by sardug10** [comment]
Hey, I am new to open source contributions. Is this a good issue to start with?

**Comment by robertlong** [comment]
Yeah, definitely a good one. It just needs to be changed here:
https://github.com/mozilla/Spoke/blob/master/src/ui/properties/SpotLightNodeEditor.js#L61

**Comment by sardug10** [comment]
> Yeah, definitely a good one. It just needs to be changed here:
> https://github.com/mozilla/Spoke/blob/master/src/ui/properties/SpotLightNodeEditor.js#L61

Hey, instead of unit="°" , I just have to change it to unit="cd". Is it?😃
